package:
  name: nspdk
  version: 9.2

source:
  fn: PGMAsimple-0.1.tar.gz
  url: https://raw.githubusercontent.com/BackofenLab/GraphClust/master/pgma_src/PGMAsimple-0.1.tar.gz
  sha256: c11534a7606dec9fbde0509cf790515dfcb68b550568ef3e1c0eab50f427d5b5

build:
  number: 0

requirements:
  build:
    - gcc   # [not osx]
    - zlib  # [not osx]

  run:
    - libgcc  # [not osx]
    - zlib    # [not osx]  

test:
  commands:
    - NSPDK -h >/dev/null

about:
  home: https://github.com/BackofenLab/GraphClust
  license: GNUv3
  license_file: 
  summary: Pgma is a simple program for building WPGMA trees.
